#!/usr/bin/python3

from os import path
import os 

src = path.join(os.path.abspath(os.curdir), 'nvim')
dest = path.expanduser('~/.config/nvim')

try:
    os.symlink(src, dest)
except Exception as e:
    print("Could not link vim directory")

src = path.join(os.path.abspath(os.curdir), 'nvim/init.vim')
dest = path.expanduser('~/.nvimrc')

try:
    os.symlink(src, dest)
except Exception as e:
    print("Could not link nvimrc")

