#!/usr/bin/env python3

from os import path
import os 
import subprocess

src = path.join(os.path.abspath(os.curdir), 'nvim')
dest = path.expanduser('~/.config/nvim')

try:
    os.symlink(src, dest)
except Exception as e:
    print("Could not link nvim directory %s" % e)

try:
    os.symlink(src, dest)
except Exception as e:
    print("Could not link nvimrc")

