colorscheme zenburn 

def ide %{
    rename-client main
    set global jumpclient main

    new rename-client tools
    set global toolsclient tools

    new rename-client docs
    set global docsclient docs
}


def -docstring 'invoke fzf to open a file' \
fzf-file %{ %sh{
    if [ -z "$TMUX" ]; then
        echo echo only works inside tmux
    else
        FILE=$(find * -type f | fzf-tmux -d 15)
        if [ -n "$FILE" ]; then
            printf 'eval -client %%{%s} edit %%{%s}\n' "${kak_client}" "${FILE}" | kak -p "${kak_session}"
        fi
    fi
} }

def -docstring 'invoke fzf to select a buffer' \
fzf-buffer %{ %sh{
    if [ -z "$TMUX" ]; then
        echo echo only works inside tmux
    else
        BUFFER=$(printf %s\\n "${kak_buflist}" | tr : '\n' | fzf-tmux -d 15)
        if [ -n "$BUFFER" ]; then
            echo "eval -client '$kak_client' 'buffer ${BUFFER}'" | kak -p ${kak_session}
        fi
    fi
} }


map global user f :fzf-file<ret>

# map global user r :source<space>/home/alex/.config/kak/kakrc<ret>

# set global ycmd_path "~/.vim/plugged/YouCompleteMe/"

# hook global WinSetOption filetype=cpp %{ ycmd-enable-autocomplete }
# hook global WinSetOption filetype=(?!cpp).* %{ ycmd-disable-autocomplete }


